services:
  db:
    image: postgres:16
    container_name: customers-db

    environment:
      POSTGRES_DB: customers_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - app-network

  api:
    build:
      context: ../api
      dockerfile: Dockerfile

    container_name: customers-api

    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: customers_db
      DB_USER: postgres
      DB_PASSWORD: postgres

    ports:
      - "3000:3000"

    depends_on:
      - db

    networks:
      - app-network

  front:
    build:
      context: ../front
      dockerfile: Dockerfile

    container_name: customers-front

    ports:
      - "8080:80"

    depends_on:
      - api

    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
